language: go

go:
  - 1.12.x

env:
  - GOARCH=amd64 GO111MODULE=off # CODECOV_TOKEN="7bc84064-5397-473d-991a-c34c91547e8a" 
  - GOARCH=amd64 GO111MODULE=on GOPROXY=https://goproxy.io

sudo: true

go_import_path: github.com/fwhezfwhez/model_convert

before_install:
  # - go get -t -v ./...
  - go get github.com/fwhezfwhez/errorx
  - git clone -b v1.4.0 https://github.com/go-sql-driver/mysql.git ${GOPATH}/src/github.com/go-sql-driver/mysql

script:
  - go test -run ^TestDone$

after_success:
  # - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false