// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user_info.proto

package userProto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserInfo struct {
	Arr                  []*ArrayElement `protobuf:"bytes,1,rep,name=arr,proto3" json:"arr,omitempty"`
	Config2              []byte          `protobuf:"bytes,2,opt,name=config2,proto3" json:"config2,omitempty"`
	Config               []byte          `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	Username             string          `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Password             string          `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	Age                  int32           `protobuf:"varint,6,opt,name=age,proto3" json:"age,omitempty"`
	Id                   int32           `protobuf:"varint,7,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_84fe32b1d3884b9c, []int{0}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetArr() []*ArrayElement {
	if m != nil {
		return m.Arr
	}
	return nil
}

func (m *UserInfo) GetConfig2() []byte {
	if m != nil {
		return m.Config2
	}
	return nil
}

func (m *UserInfo) GetConfig() []byte {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *UserInfo) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserInfo) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UserInfo) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *UserInfo) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ArrayElement struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArrayElement) Reset()         { *m = ArrayElement{} }
func (m *ArrayElement) String() string { return proto.CompactTextString(m) }
func (*ArrayElement) ProtoMessage()    {}
func (*ArrayElement) Descriptor() ([]byte, []int) {
	return fileDescriptor_84fe32b1d3884b9c, []int{1}
}

func (m *ArrayElement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArrayElement.Unmarshal(m, b)
}
func (m *ArrayElement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArrayElement.Marshal(b, m, deterministic)
}
func (m *ArrayElement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArrayElement.Merge(m, src)
}
func (m *ArrayElement) XXX_Size() int {
	return xxx_messageInfo_ArrayElement.Size(m)
}
func (m *ArrayElement) XXX_DiscardUnknown() {
	xxx_messageInfo_ArrayElement.DiscardUnknown(m)
}

var xxx_messageInfo_ArrayElement proto.InternalMessageInfo

func init() {
	proto.RegisterType((*UserInfo)(nil), "userProto.UserInfo")
	proto.RegisterType((*ArrayElement)(nil), "userProto.ArrayElement")
}

func init() { proto.RegisterFile("user_info.proto", fileDescriptor_84fe32b1d3884b9c) }

var fileDescriptor_84fe32b1d3884b9c = []byte{
	// 201 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x2d, 0x4e, 0x2d,
	0x8a, 0xcf, 0xcc, 0x4b, 0xcb, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x04, 0x09, 0x04,
	0x80, 0x98, 0x4a, 0x07, 0x19, 0xb9, 0x38, 0x42, 0x8b, 0x53, 0x8b, 0x3c, 0xf3, 0xd2, 0xf2, 0x85,
	0x34, 0xb9, 0x98, 0x13, 0x8b, 0x8a, 0x24, 0x18, 0x15, 0x98, 0x35, 0xb8, 0x8d, 0xc4, 0xf5, 0xe0,
	0xaa, 0xf4, 0x1c, 0x8b, 0x8a, 0x12, 0x2b, 0x5d, 0x73, 0x52, 0x73, 0x53, 0xf3, 0x4a, 0x82, 0x40,
	0x6a, 0x84, 0x24, 0xb8, 0xd8, 0x93, 0xf3, 0xf3, 0xd2, 0x32, 0xd3, 0x8d, 0x24, 0x98, 0x14, 0x18,
	0x35, 0x78, 0x82, 0x60, 0x5c, 0x21, 0x31, 0x2e, 0x36, 0x08, 0x53, 0x82, 0x19, 0x2c, 0x01, 0xe5,
	0x09, 0x49, 0x71, 0x71, 0x80, 0x0c, 0xcc, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x51, 0x60, 0xd4, 0xe0,
	0x0c, 0x82, 0xf3, 0x41, 0x72, 0x05, 0x89, 0xc5, 0xc5, 0xe5, 0xf9, 0x45, 0x29, 0x12, 0xac, 0x10,
	0x39, 0x18, 0x5f, 0x48, 0x80, 0x8b, 0x39, 0x31, 0x3d, 0x55, 0x82, 0x4d, 0x81, 0x51, 0x83, 0x35,
	0x08, 0xc4, 0x14, 0xe2, 0xe3, 0x62, 0xca, 0x4c, 0x91, 0x60, 0x07, 0x0b, 0x30, 0x65, 0xa6, 0x28,
	0xf1, 0x71, 0xf1, 0x20, 0x3b, 0x30, 0x89, 0x0d, 0xec, 0x4b, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x4c, 0x4f, 0xa9, 0xa6, 0xf8, 0x00, 0x00, 0x00,
}
